apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-i2hu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-i2hu@sha256:1fba45e5aa581c63ca07c776663c8e64068664f00af8a757118079bd9750747a
        name: my-nodejs
        resources: {}
status: {}
